<a href="https://colab.research.google.com/github/vivianatuarez/UEES-IA-Semana1-TuarezViviana/blob/main/01_Fundamentos_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# === CONEXIÓN AUTOMÁTICA CON GITHUB (EJECUTAR UNA VEZ POR SESIÓN) ===
from google.colab import auth
auth.authenticate_user()

import os
from getpass import getpass

# Ingresa tu usuario y token de GitHub
repo_name = "UEES-IA-Semana1-TuarezViviana"
username = input("GitHub Username: ")
email = input("Email GitHub (tu correo UEES): ")
token = getpass("GitHub Personal Access Token (genera uno en Settings > Developer settings > Tokens): ")

!git config --global user.email "{email}"
!git config --global user.name "{username}"

# Clonar el repositorio
!git clone https://{token}@github.com/{username}/{repo_name}.git
%cd {repo_name}

# Crear carpetas si no existen
!mkdir -p 02_Laboratorio/notebooks 02_Laboratorio/images data

print("¡Conectado a GitHub correctamente!")

GitHub Username: vivianatuarez
Email GitHub (tu correo UEES): viviana.tuarez@uees.edu.ec
GitHub Personal Access Token (genera uno en Settings > Developer settings > Tokens): ··········
Cloning into 'UEES-IA-Semana1-TuarezViviana'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.
/content/UEES-IA-Semana1-TuarezViviana/UEES-IA-Semana1-TuarezViviana
¡Conectado a GitHub correctamente!


In [15]:
# Título en Markdown:
# # Fundamentos de NumPy y Pandas

import numpy as np
import pandas as pd

# --- NumPy ---
arr = np.random.randint(1, 100, size=(5,5))
print("Array 5x5 aleatorio:\n", arr)

print("Suma por columnas:", arr.sum(axis=0))
print("Media total:", arr.mean())

# --- Pandas ---
import seaborn as sns
titanic = sns.load_dataset('titanic')
iris = sns.load_dataset('iris')

print(titanic.head())
print(titanic.describe())
print("Supervivientes por clase:\n", titanic.groupby('class')['survived'].mean())

Array 5x5 aleatorio:
 [[ 6 99 59 12 24]
 [96 22 89 83 89]
 [20 19 66 19 61]
 [ 2 18 27  8 51]
 [23 37 68 76 60]]
Suma por columnas: [147 195 309 198 285]
Media total: 45.36
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
         survived      pclass         age     

/tmp/ipython-input-2203328293.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print("Supervivientes por clase:\n", titanic.groupby('class')['survived'].mean())


In [18]:
save_to_github("01_Fundamentos_NumPy_Pandas.ipynb", "Completado fundamentos NumPy y Pandas")

cp: cannot stat '/content/01_Fundamentos_NumPy_Pandas.ipynb': No such file or directory
On branch main

Initial commit

nothing to commit (create/copy files and use "git add" to track)
error: src refspec refs/heads/main does not match any
error: failed to push some refs to 'https://github.com/vivianatuarez/UEES-IA-Semana1-TuarezViviana.git'
✅ 01_Fundamentos_NumPy_Pandas.ipynb guardado en GitHub con éxito


In [19]:
# Verificar si estamos en Google Colab
try:
    import google.colab
    IN_COLAB = True
    print(" Ejecutándose en Google Colab")
except ImportError:
    IN_COLAB = False
    print(" No está en Google Colab")

# Verificar recursos disponibles en Colab
if IN_COLAB:
    # Verificar GPU disponible
    import tensorflow as tf
    print(" Verificando recursos de hardware:")
    print(f"   - GPUs disponibles: {len(tf.config.list_physical_devices('GPU'))}")

    if len(tf.config.list_physical_devices('GPU')) > 0:
        print("   - Tipo GPU:", tf.config.list_physical_devices('GPU')[0])
        print("    GPU activada - Ideal para Deep Learning")
    else:
        print("     Solo CPU disponible - Suficiente para esta práctica")

    # Verificar RAM disponible
    import psutil
    ram_gb = round(psutil.virtual_memory().total / (1024**3), 1)
    print(f"   - RAM disponible: {ram_gb} GB")
    print(f"   - Almacenamiento temporal: ~100GB")

# Instalar librerías adicionales específicas para Colab
if IN_COLAB:
    print("\n Instalando librerías adicionales en Colab...")
    !pip install -q plotly kaleido  # Para gráficos interactivos
    !pip install -q seaborn --upgrade  # Asegurar última versión
    print(" Instalación completada")

 Ejecutándose en Google Colab
 Verificando recursos de hardware:
   - GPUs disponibles: 0
     Solo CPU disponible - Suficiente para esta práctica
   - RAM disponible: 12.7 GB
   - Almacenamiento temporal: ~100GB

 Instalando librerías adicionales en Colab...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 3.3 MB/s eta 0:00:00
 Instalación completada


In [20]:
# Importaciones optimizadas para Colab
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Importaciones específicas para ML/DL
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Configuración específica para Colab
import warnings
warnings.filterwarnings('ignore')

# Configuración de visualización optimizada para Colab
plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (12, 8)  # Más grande para pantallas Colab
plt.rcParams['font.size'] = 12
plt.rcParams['figure.dpi'] = 100  # Mejor resolución en Colab

# Configurar plotly para Colab
import plotly.io as pio
pio.renderers.default = 'colab'  # Renderizado específico para Colab

print("\n Configuración específica para Google Colab completada")
print("=" * 60)


 Configuración específica para Google Colab completada


In [21]:
# ========================================================================
# CARGAR DATOS ESPECÍFICO PARA COLAB
# ========================================================================

print("\n CARGANDO DATOS EN GOOGLE COLAB")
print("=" * 40)

# Opción 1: Datasets integrados en Colab (más rápido)
print("Método 1: Datasets integrados en Seaborn")
titanic = sns.load_dataset('titanic')
tips = sns.load_dataset('tips')
flights = sns.load_dataset('flights')

print(f" Titanic dataset: {titanic.shape}")
print(f" Tips dataset: {tips.shape}")
print(f" Flights dataset: {flights.shape}")


 CARGANDO DATOS EN GOOGLE COLAB
Método 1: Datasets integrados en Seaborn
 Titanic dataset: (891, 15)
 Tips dataset: (244, 7)
 Flights dataset: (144, 3)
